/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __com_androidyuan_tool_JavaCallC__
#define __com_androidyuan_tool_JavaCallC__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jstring JNICALL Java_com_androidyuan_tool_JavaCallC_getString (JNIEnv *env, jclass);
JNIEXPORT void JNICALL Java_com_androidyuan_tool_JavaCallC_setStreamListener (JNIEnv *env, jclass, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __com_androidyuan_tool_JavaCallC__ */
